name: Fetch latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -L 'https://download.beta.ons.gov.uk/downloads/datasets/weekly-deaths-region/editions/covid-19/versions/20.csv' -o weekly-deaths-region.csv --no-progress-meter
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
